# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodWise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'ImageSlideshow', '~> 1.9.0'
  # Pods for FoodWise

  target 'FoodWiseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodWiseUITests' do
    # Pods for testing
  end

end
